# Generated by Django 5.2.5 on 2025-08-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="email",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="email",
            name="id",
        ),
        migrations.AddField(
            model_name="email",
            name="email_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="email",
            name="thread_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="email",
            name="parent_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="emails.email",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="receiver",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
